---
name: release-on-tag-creation
run-name: Creating a release on ${{ github.ref_name }} ${{ github.ref_type }}
on:
  workflow_dispatch:
  # push:
  # tags:
  # - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build x86_64 glib2.28
        run: |
          # test
          make release-arm
          ls -alh ./target/armv7-unknown-linux-gnueabihf/release/
